# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once =  [workspace 1 silent] uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" bash -c "tmux attach || tmux new -s "
exec-once = [workspace 2 silent] uwsm-app -- firefox
