# Status bar
set -g window-status-separator "  "

# Theme
set -g status-style 'bg=default fg=#5eacd3'
set -g status-right "#[fg=default]#{?pane_in_mode,COPY ,}#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg=brightblack]#{pane_current_path}"
set -g window-status-format "#[fg=brightblack] #I:#W "
